'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

type F={date:string;district_code:string;district:string;division:string;gfs_forecast_mm:number;ifs_hres_forecast_mm:number;aifs_forecast_mm:number;weight_gfs:number;weight_ifs_hres:number;weight_aifs:number;synapse_wx_forecast_mm:number;rainfall_category:string;confidence_level:string;model_agreement_mm:number;trust_explanation:string;imd_actual_mm:number;absolute_error_mm:number};
type Feature={properties:{district_code:number;district:string;division:string};geometry:{type:string;coordinates:any}};type Geo={features:Feature[]};
const Icon=({children}:{children:string})=><span className="icon" aria-hidden="true">{children}</span>;
const DIVS=['All','Coastal Karnataka','North Interior Karnataka','South Interior Karnataka'];
const C:Record<string,string>={dry:'#24344d',very_light:'#79e7db',light:'#26c7c9',moderate:'#2b8fe5',rather_heavy:'#7d6cf2',heavy:'#b15ee8',very_heavy:'#f06cae',extremely_heavy:'#ff556f'};
const L:Record<string,string>={dry:'Dry',very_light:'Very light',light:'Light',moderate:'Moderate',rather_heavy:'Rather heavy',heavy:'Heavy',very_heavy:'Very heavy',extremely_heavy:'Extremely heavy'};
function csv(t:string){const z:string[][]=[];let r:string[]=[],c='',q=false;for(let i=0;i<t.length;i++){const x=t[i];if(x==='"'){if(q&&t[i+1]==='"'){c+='"';i++}else q=!q}else if(x===','&&!q){r.push(c);c=''}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&t[i+1]==='\n')i++;r.push(c);if(r.some(Boolean))z.push(r);r=[];c=''}else c+=x}const h=z.shift()!;const n=new Set(['gfs_forecast_mm','ifs_hres_forecast_mm','aifs_forecast_mm','weight_gfs','weight_ifs_hres','weight_aifs','synapse_wx_forecast_mm','model_agreement_mm','imd_actual_mm','absolute_error_mm']);return z.map(v=>Object.fromEntries(h.map((k,i)=>[k,n.has(k)?Number(v[i]):v[i]])) as F)}
const rings=(f:Feature):number[][][]=>f.geometry.type==='Polygon'?f.geometry.coordinates:f.geometry.coordinates.flatMap((p:any)=>p);
function MapView({geo,records,selected,onSelect}:{geo:Geo;records:Map<string,F>;selected:string;onSelect:(x:string)=>void}){const[tip,setTip]=useState<{f:Feature;x:number;y:number}|null>(null),pts=geo.features.flatMap(f=>rings(f).flat()),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),mnx=Math.min(...xs),mxx=Math.max(...xs),mny=Math.min(...ys),mxy=Math.max(...ys),w=560,h=610,p=20,s=Math.min((w-p*2)/(mxx-mnx),(h-p*2)/(mxy-mny)),xy=(a:number[])=>[(a[0]-mnx)*s+p,h-p-(a[1]-mny)*s],path=(f:Feature)=>rings(f).map(a=>a.map((v,i)=>`${i?'L':'M'}${xy(v)[0].toFixed(1)},${xy(v)[1].toFixed(1)}`).join(' ')+' Z').join(' ');
return <div className="map-stage"><i className="orbit a"/><i className="orbit b"/><svg className="state-map" viewBox={`0 0 ${w} ${h}`} role="group" aria-label="Interactive Karnataka district rainfall map"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{geo.features.map(f=>{const k=String(f.properties.district_code),v=records.get(k);return <path key={k} d={path(f)} tabIndex={0} role="button" aria-label={`${f.properties.district}: ${v?v.synapse_wx_forecast_mm.toFixed(1)+' millimetres, '+L[v.rainfall_category]:'not shown'}`} className={'district '+(k===selected?'selected':'')} fill={C[v?.rainfall_category||'dry']||C.dry} onClick={()=>onSelect(k)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(k)}}} onMouseMove={e=>setTip({f,x:e.clientX,y:e.clientY})} onMouseLeave={()=>setTip(null)}/>} )}</svg>{tip&&(()=>{const v=records.get(String(tip.f.properties.district_code));return <div className="tooltip" style={{left:Math.min(tip.x+15,innerWidth-230),top:Math.max(10,tip.y-90)}}><b>{tip.f.properties.district}</b><span>{v?`${v.synapse_wx_forecast_mm.toFixed(1)} mm · ${L[v.rainfall_category]}`:'Filtered out'}</span>{v&&<small>{v.confidence_level} confidence</small>}</div>})()}</div>}
function Count({v}:{v:number}){const[x,setX]=useState(v),old=useRef(v);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setX(v);return}let id=0,st=performance.now(),a=old.current;old.current=v;const go=(t:number)=>{let p=Math.min(1,(t-st)/500);setX(a+(v-a)*(1-(1-p)**3));if(p<1)id=requestAnimationFrame(go)};id=requestAnimationFrame(go);return()=>cancelAnimationFrame(id)},[v]);return <>{x.toFixed(1)}</>}
function Model({n,v,w,color}:{n:string;v:number;w:number;color:string}){return <article className="model" style={{'--tone':color} as React.CSSProperties}><div><span><i/>{n}</span><b>{v.toFixed(1)} <small>mm</small></b></div><div className="trust"><span>Adaptive trust</span><b>{(w*100).toFixed(1)}%</b></div><div className="track"><i style={{width:`${w*100}%`}}/></div></article>}
export default function Home(){const[data,setData]=useState<F[]>([]),[geo,setGeo]=useState<Geo|null>(null),[err,setErr]=useState(''),[date,setDate]=useState('2026-08-31'),[div,setDiv]=useState('All'),[code,setCode]=useState('525'),[search,setSearch]=useState('');useEffect(()=>{Promise.all([fetch('/data/forecasts.csv').then(r=>r.ok?r.text():Promise.reject(Error('Forecast data could not be loaded'))),fetch('/data/districts.geojson').then(r=>r.ok?r.json():Promise.reject(Error('Map data could not be loaded')))]).then(([a,b])=>{setData(csv(a));setGeo(b)}).catch(e=>setErr(e.message))},[]);const dates=useMemo(()=>[...new Set(data.map(x=>x.date))].sort(),[data]),idx=Math.max(0,dates.indexOf(date)),records=useMemo(()=>new Map(data.filter(x=>x.date===date&&(div==='All'||x.division===div)).map(x=>[x.district_code,x])),[data,date,div]),sel=data.find(x=>x.date===date&&x.district_code===code)||data.find(x=>x.date===date&&(div==='All'||x.division===div)),found=useMemo(()=>[...new Map(data.filter(x=>div==='All'||x.division===div).map(x=>[x.district_code,x])).values()].filter(x=>x.district.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.district.localeCompare(b.district)),[data,div,search]);useEffect(()=>{if(sel&&div!=='All'&&sel.division!==div){const n=data.find(x=>x.date===date&&x.division===div);if(n)setCode(n.district_code)}},[div,date,data,sel]);if(err)return <main className="state"><Icon>!</Icon><h1>Dashboard data unavailable</h1><p>{err}. Check the local data files and refresh.</p></main>;if(!geo||!data.length)return <main className="state"><Icon>☂</Icon><h1>Loading statewide hindcast</h1><p>Preparing 31 districts and 3,749 verified records…</p></main>;if(!sel)return null;const move=(n:number)=>setDate(dates[Math.max(0,Math.min(dates.length-1,idx+n))]);return <main className="shell">
<header><div className="brand"><div className="logo"><Icon>☂</Icon></div><div><div className="brandline"><h1>SYNAPSE-WX</h1><span>Historical-performance MVP</span></div><p>Adaptive district rainfall forecasting for Karnataka</p></div></div><div className="chips"><i className="gfs">GFS</i><i className="ifs">IFS HRES</i><i className="aifs">AIFS</i><i className="syn">SYNAPSE-WX</i></div></header>
<div className="ribbon"><span><i/> Historical hindcast — not a live forecast</span><span><Icon>▦</Icon> 3,749 district-day records</span><span><Icon>✓</Icon> Frozen model · Test period</span></div>
<div className="grid"><aside className="panel controls"><div className="heading"><div><small>CONTROL DECK</small><h2>Explore hindcast</h2></div><Icon>◉</Icon></div><label className="search"><Icon>⌕</Icon><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search district…" aria-label="Search district"/></label>{search&&<div className="results">{found.slice(0,6).map(x=><button key={x.district_code} onClick={()=>{setCode(x.district_code);setSearch('')}}>{x.district}<span>{x.division.replace(' Karnataka','')}</span></button>)}{!found.length&&<p>No districts found</p>}</div>}
<section><label>Division</label><div className="divs">{DIVS.map(x=><button key={x} className={div===x?'active':''} onClick={()=>setDiv(x)}>{x}</button>)}</div></section><section><div className="labelrow"><label>Valid date</label><span>{new Date(date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</span></div><div className="timeline"><button onClick={()=>move(-1)} disabled={!idx} aria-label="Previous date">‹</button><input type="range" min="0" max={dates.length-1} value={idx} onChange={e=>setDate(dates[+e.target.value])}/><button onClick={()=>move(1)} disabled={idx===dates.length-1} aria-label="Next date">›</button></div><div className="ends"><span>01 May</span><span>31 Aug 2026</span></div></section><section><label>Rainfall category</label><div className="legend">{Object.entries(L).map(([k,v])=><div key={k}><i style={{background:C[k]}}/>{v}</div>)}</div></section><div className="mode"><Icon>▣</Icon><div><small>DATA MODE</small><b>Historical Hindcast</b><span>Final held-out test: May–Aug 2026</span></div></div></aside>
<section className="map panel"><div className="heading"><div><small>STATEWIDE OVERVIEW</small><h2>Karnataka rainfall field</h2></div><div className="shown">Showing <b>{records.size} districts</b></div></div><MapView geo={geo} records={records} selected={sel.district_code} onSelect={setCode}/><footer><span><Icon>▣</Icon> Selected valid date</span><b>{new Date(date+'T00:00:00').toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</b></footer></section>
<aside className="panel insight"><div className="kicker"><span><Icon>⌖</Icon> Selected district</span><b>{sel.district_code}</b></div><h2>{sel.district}</h2><p className="division">{sel.division}</p><p className="date">{new Date(date+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'})}</p><div className="hero"><small>SYNAPSE-WX FORECAST</small><div><b><Count v={sel.synapse_wx_forecast_mm}/></b><span>mm</span></div><p><i style={{'--cat':C[sel.rainfall_category]} as React.CSSProperties}>{L[sel.rainfall_category]}</i><i className={sel.confidence_level}>{sel.confidence_level} confidence</i></p></div><div className="agreement"><div><span>Model agreement</span><b>{sel.model_agreement_mm.toFixed(2)} mm</b></div><small>Spread across the three source forecasts</small></div><div className="verify"><div><Icon>✓</Icon><p><b>Verification only</b><span>Post-forecast verification only</span></p></div><section><p><span>IMD actual rainfall</span><b>{sel.imd_actual_mm.toFixed(1)} mm</b></p><p><span>Absolute error</span><b>{sel.absolute_error_mm.toFixed(1)} mm</b></p></section></div><div className="models"><Model n="GFS" v={sel.gfs_forecast_mm} w={sel.weight_gfs} color="#3388ff"/><Model n="IFS HRES" v={sel.ifs_hres_forecast_mm} w={sel.weight_ifs_hres} color="#ffb24a"/><Model n="AIFS" v={sel.aifs_forecast_mm} w={sel.weight_aifs} color="#a878ff"/></div><div className="note"><small>WHY THIS BLEND?</small><p>{sel.trust_explanation.replace(/Historical hindcast[^.]*\.\s*/i,'')}</p></div></aside></div></main>}
